# Generated by Django 4.1.5 on 2023-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=250)),
                ('year_made', models.TextField(max_length=500)),
                ('img', models.DateTimeField(max_length=500)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
